### ISSUE TITLE
remove single quotes

### ISSUE THREAD

**Issue by lucadelu** [veroandreo/i.landsat#1]
https://github.com/veroandreo/i.landsat/blob/c2b84912ce14b0f79a24aa77c4366405df09ea64/i.landsat.download/i.landsat.download.py#L105

should be replaced with

`return (info['w'], info['s'], info['e'], info['n'])`

in this way you return a tuple with the four value

**Comment by veroandreo** [comment]
Thanks a lot! Fixed in https://github.com/veroandreo/i.landsat/commit/0c79cb4fdc08a76abc858414fcb3128923669543
