### ISSUE TITLE
Use parse_command instead of read_command and parse_key_values

### ISSUE THREAD

**Issue by ninsbl** [veroandreo/i.landsat#10]
These two lines:
https://github.com/veroandreo/i.landsat/blob/24787b84f1ac4c6957f3809a4f50452bf7d840e1/i.landsat.download/i.landsat.download.py#L93-L94
could be merged to one:
`kv = gs.parse_command("g.proj", flags='j')`

Only a little relevant detail though...

**Comment by veroandreo** [comment]
Thanks @ninsbl !!
