### ISSUE TITLE
What happens with invalid scene IDs

### ISSUE THREAD

**Issue by ninsbl** [veroandreo/i.landsat#11]
Will this fail with invalid IDs
https://github.com/veroandreo/i.landsat/blob/f1509c56024dbfd05285885b7b38acf22dff671e/i.landsat.download/i.landsat.download.py#L169-L173
?

**Comment by veroandreo** [comment]
The IDs should look like `LC80160352018244LGN00`. How could I test for that or catch the error moreover?

**Comment by ninsbl** [comment]
I would just wrap the download in a try-except-statement and give e.g. a warning message if an ID is not found (or error message if you want to be more strict) in the except part.

**Comment by veroandreo** [comment]
Would that be fine?

**Comment by ninsbl** [comment]
> Would that be fine?

You could add the invalid scene ID to the message though:
`gs.fatal(_("Scene ID <{}> not valid or not found.".format(i)))`
That would make it easier for the user to discover what he/she did wrong...

Also, the directory option should be validated earlier (at the beginning of main() actually):
Something like this:

```
if os.is_dir(directory):
    if not os.access(directory, os.W_OK):
        gs.fatal("Not writable")
else:
    gs.fatal("Not a directory")
```

But thinking about it, maybe the parser does that check !?!

**Comment by veroandreo** [comment]
There was a problem in https://github.com/veroandreo/i.landsat/commit/4fdcdc1a74f41989289597b93b4bb42e8e7de663.
 Now, I fixed it in https://github.com/veroandreo/i.landsat/commit/9639d3b39ded34244bd4e81d80145713870c59fa. Seems to work as expected
