### ISSUE TITLE
i.landsat.import: add `pattern` and `pattern_file` options

### ISSUE THREAD

**Issue by veroandreo** [veroandreo/i.landsat#14]
i.landsat.import is now a very simple module to import all Landsat bands from the *input* or *unzip_dir* directories. More options should be added to allow to select which bands to import or which .tar.gz files to unzip (e.g. only those of a certain path an row).

**Comment by ninsbl** [comment]
See https://docs.python.org/3/library/tarfile.html#tarfile.TarFile.getmembers / https://docs.python.org/3/library/tarfile.html#tarfile.TarFile.getnames
to get a list of files that can be filtered using a regular expression.

**Comment by veroandreo** [comment]
thanks @ninsbl ! I was just working on this before reading here. I used `shutil.unpack_archive()` instead of tarfile. Shall I change that?

**Comment by veroandreo** [comment]
Comment to self: 
See also https://github.com/veroandreo/i.landsat/issues/16#issuecomment-742844484
