### ISSUE TITLE
i.landsat.import: add option to write a t.register file 

### ISSUE THREAD

**Issue by veroandreo** [veroandreo/i.landsat#15]
In the case of downloading and importing a time series of landsat data, it would be great to have an output with the file to register such scenes in the temporal database.

**Comment by ninsbl** [comment]
Would a timestamp and an increment work, instead of a register file?

**Comment by veroandreo** [comment]
> Would a timestamp and an increment work, instead of a register file?

I don't think so. According to search criteria, users will hardly ever have landsat data at regular intervals as to use the increment option, I think. The idea would be to get file name and start_time per imported band. 

I need to study how to use g.band/i.bands, too. Maybe, we could think of adding another flag so bands get their 'tag' and can then be registered as an image collection.

**Comment by ninsbl** [comment]
Yes, you are right.
