### ISSUE TITLE
strange print call

### ISSUE THREAD

**Issue by lucadelu** [veroandreo/i.landsat#2]
https://github.com/veroandreo/i.landsat/blob/c2b84912ce14b0f79a24aa77c4366405df09ea64/i.landsat.download/i.landsat.download.py#L142

Are you sure that you have to print() it?

**Comment by veroandreo** [comment]
Fixed in https://github.com/veroandreo/i.landsat/commit/0c79cb4fdc08a76abc858414fcb3128923669543. Thanks!
