### ISSUE TITLE
move landsatxplore.api.API call

### ISSUE THREAD

**Issue by lucadelu** [veroandreo/i.landsat#3]
https://github.com/veroandreo/i.landsat/blob/c2b84912ce14b0f79a24aa77c4366405df09ea64/i.landsat.download/i.landsat.download.py#L121

https://github.com/veroandreo/i.landsat/blob/c2b84912ce14b0f79a24aa77c4366405df09ea64/i.landsat.download/i.landsat.download.py#L132

I suggest to move this call later after you check if user and password are set so you have just a place where you call the function

**Comment by veroandreo** [comment]
Thanks for the suggestion! Fixed in https://github.com/veroandreo/i.landsat/commit/0c79cb4fdc08a76abc858414fcb3128923669543
