### ISSUE TITLE
define a function to retrieve central coords of vector map or region

### ISSUE THREAD

**Issue by veroandreo** [veroandreo/i.landsat#4]
Similar to `get_bb()` and because right now, it does not seem to work properly in the landsatxplore library itself (see [this issue](https://github.com/yannforget/landsatxplore/issues/23)), it would be nice to also have a function to retrieve central coordinates of the vector extent or region. In this way, we can pass those coordinates to the `longitude` and `latitude` parameters in the api. 

Shall we also expose them as parameters of the module? What do you think @lucadelu?

**Comment by lucadelu** [comment]
I saw in you example in the issue that the bbox parameters are string instead of number, try with number if it solve the problem.

I think you should not expose them as parameters of the module, in the case you can get them for the bbox

**Comment by veroandreo** [comment]
It seems documentation is wrong according to yann's answer in the issue. Seems that x and y were confused. I'll test changing the order of coordinates. I do not think it is a string vs number problem, but let's see.

**Comment by veroandreo** [comment]
Fixing coordinates order as suggested by yann [here](https://github.com/yannforget/landsatxplore/issues/23#issuecomment-727862809), solves the problem. Closing.
