### ISSUE TITLE
create filter for tiers

### ISSUE THREAD

**Issue by veroandreo** [veroandreo/i.landsat#5]
Landsat Collection 1 data comes in 3 tiers: Real Time, Tier 1 and Tier 2. From those, Tier 1 (T1) is regarded as the best one for time series analysis. Tier 2, instead, has less accurate orbital information (specific to older Landsat sensors), significant cloud cover, insufficient ground control, or other factors. 

This information is stored in the filename, esp in the `displayId` field. It would be cool to add a parameter to filter results by tier.

**Comment by ninsbl** [comment]
This:
`scenes = list(filter(lambda s: "T1" in s['displayId'], scenes))`
would filter (=keep) all scenes with the string "T1" in the "displayId" (note: you might need different filter criteria)

**Comment by veroandreo** [comment]
`tier`option added in https://github.com/veroandreo/i.landsat/commit/9639d3b39ded34244bd4e81d80145713870c59fa

**Comment by ninsbl** [comment]
Just make sure that RT, T1 and T2 are specific enought to be used for filtering. If the combination of those two letters can occur at other places in the displayId, you will get unwanted results. I don`t know the naming convention for those data. Maybe it is no problem, but maybe you have to make the filter more precise (e.g. by taking position into account).

**Comment by veroandreo** [comment]
This is how names look like according to [docs](https://www.usgs.gov/core-science-systems/nli/landsat/landsat-collection-1?qt-science_support_page_related_con=1#qt-science_support_page_related_con):

Real-Time: LE07_L1GT_037035_20160314_20160314_01_RT
Tier 1: LE07_L1TP_016039_20040918_20160211_01_T1
Tier 2: LT04_L1GS_017036_19821115_20160315_01_T2

Should I also add the `_` to the pattern ??

**Comment by ninsbl** [comment]
OK, then it should not be an issue.
If the tier is allways the last two characters you might use `s['displayId'].endswith(tier)` function or indexing the last two characters `s['displayId'][-2:] == tier`

**Comment by veroandreo** [comment]
Cool, thanks for checking and suggesting alternatives! I really appreciate your help!
I'll close this one for now
