### ISSUE TITLE
download all scenes found when -l is not set and id is not provided

### ISSUE THREAD

**Issue by veroandreo** [veroandreo/i.landsat#6]
Setting -l should print the scenes found, not setting it should download all of them. Using an id or a list of ids is a separate option.

**Comment by ninsbl** [comment]
When options and flags get related to each other (e.g. when -l oand id option are mutually exclusive), these relations can be conveniently controled by parser rules.
See:
https://grass.osgeo.org/grass78/manuals/g.parser.html
for more info on that.

**Comment by veroandreo** [comment]
Code added and re-structured as suggested by Luca. To be tested when EarthExplorer is back.

**Comment by veroandreo** [comment]
it now prints the list when -l is set and it starts the download when -l is not provided...
closing
