### ISSUE TITLE
add option to sort scenes by date or cloud cover (ascending and descending)

### ISSUE THREAD

**Issue by veroandreo** [veroandreo/i.landsat#8]
This would probably mean to create a table with scenes found, so then I can sort it by columns

**Comment by ninsbl** [comment]
No need to create a table. You could sort the list of dictionaries you get from the API-call directly.

See e.g. here: https://careerkarma.com/blog/python-sort-a-dictionary-by-value/ for n example on how to sort a dict...
E.g. 
`sorted(scenes, key=lambda i: (i['cloudCover'],i['acquisitionDate'])) 
`
would sort by 1. cloud cover and 2. date'.

**Comment by veroandreo** [comment]
@ninsbl and @lucadelu would you have a look at the last commit? I realized late that I should have created a branch and a PR, but well... I really appreciate your help! :-) 

EarthExplorer is down for maintenance, so I can't test at least for a couple more hours...

**Comment by lucadelu** [comment]
I think download all scenes will not work because sorted_scenes seems to not be defined.

As the code is written probably could be better to change the if: if options['id'] is present you download that scenes otherwise you first search for all the scenes and later if flag[l] is present you print the data otherwise you dowload

**Comment by veroandreo** [comment]
> I think download all scenes will not work because sorted_scenes seems to not be defined.

I should do something like `sorted_scenes = {}`? Is that right?

> As the code is written probably could be better to change the if: if options['id'] is present you download that scenes otherwise you first search for all the scenes and later if flag[l] is present you print the data otherwise you dowload

ok

**Comment by veroandreo** [comment]
Thanks @lucadelu ! 

I have now re-structured the code as you suggested: https://github.com/veroandreo/i.landsat/commit/0c4bcc36bb4264862965980ad2416a69d65e57e0

What do you think?

**Comment by lucadelu** [comment]
Seems to  be good

**Comment by veroandreo** [comment]
> No need to create a table. You could sort the list of dictionaries you get from the API-call directly.
> 
> See e.g. here: https://careerkarma.com/blog/python-sort-a-dictionary-by-value/ for n example on how to sort a dict...
> E.g.
> `sorted(scenes, key=lambda i: (i['cloudCover'],i['acquisitionDate'])) `
> would sort by 1. cloud cover and 2. date'.

it works in a python script:
`sorted_scenes = sorted(scenes, key=lambda i: (i['acquisitionDate'],i['cloudCover']))`

but not within the module, when I do:
```
sort_vars = options['sort'].split(',')

reverse = ''
if options['order'] == 'desc':
    reverse = True

sorted_scenes = sorted(scenes, key=lambda i: (i[sort_vars[0]],i[sort_vars[1]]),
                               reverse = reverse)
```

I get the following error:

```
Traceback (most recent call last):
  File "./i.landsat.download.py", line 240, in <module>
    main()
  File "./i.landsat.download.py", line 201, in main
    sorted_scenes = sorted(scenes, key=lambda i: (i[sort_vars[0]],i[sort_vars[1]]),
TypeError: an integer is required (got type str)
```

**Comment by ninsbl** [comment]
You would need to do:
```
sorted_scenes = sorted(scenes, key=lambda i: (i[sort_vars[0]],i[sort_vars[1]]),
                               reverse = True)
```
or
```
sorted_scenes = sorted(scenes, key=lambda i: (i[sort_vars[0]],i[sort_vars[1]]),
                               reverse = 1) # boolean as numeric
```

So, you would need to turn order option into a boolean (or 0/1).
Or you assume that the default is ascending order and have e.g. a -r flag for reverse sorting.

**Comment by veroandreo** [comment]
Thanks @ninsbl and @lucadelu (in chat)!

**Comment by veroandreo** [comment]
seems to be working now, closing
