### ISSUE TITLE
Move imports of landsatexplore after the parser and wrap in try-except

### ISSUE THREAD

**Issue by ninsbl** [veroandreo/i.landsat#9]
Imports of landsatexplore should be moved from here:
https://github.com/veroandreo/i.landsat/blob/24787b84f1ac4c6957f3809a4f50452bf7d840e1/i.landsat.download/i.landsat.download.py#L85
https://github.com/veroandreo/i.landsat/blob/24787b84f1ac4c6957f3809a4f50452bf7d840e1/i.landsat.download/i.landsat.download.py#L157

to after the parser (and before main is run) here:
https://github.com/veroandreo/i.landsat/blob/24787b84f1ac4c6957f3809a4f50452bf7d840e1/i.landsat.download/i.landsat.download.py#L174

Otherwise the manuals will not build on the built server (and the module will be unavailable on Windows).
It is also an advantage to wrap the import in a try-except-statement and give users a proper error message, instead of a traceback...

See e.g.
https://github.com/OSGeo/grass-addons/blob/98ca4366a03193e998c467c55fb095ade9d8b426/grass7/raster/r.mregression.series/r.mregression.series.py#L279
as an example.

**Comment by veroandreo** [comment]
Thanks!
